WP-978 Ionic support for saved card payment
MonriPayments/ionic-monri-android-ios pull request #3
Opened 2021-12-16 11:32 UTC by adnanomerovic

Ionic support for saved card payment
WP-978

2021-12-16 12:30 UTC, jasminsuljic commented on android/src/main/java/com/monri/ionic/IonicMonriPlugin.java
> +        } else {
Replace with else if params.getObject("params").has("saved_card").

In else you should return error, something like no card or saved card found in params. Additionally code does not seem properly formatted.

2021-12-16 12:55 UTC, jasminsuljic requested changes

2021-12-16 14:51 UTC, adnanomerovic commented on android/src/main/java/com/monri/ionic/IonicMonriPlugin.java
> +            throw new IllegalStateException("Unsupported payment method, 'card' or 'saved_card' not found");
I'll fix it in next commit.

2021-12-17 08:53 UTC, jasminsuljic approved these changes

2021-12-17 08:53 UTC, merged